use_frameworks!

platform :ios, '10.0'

target 'CTM_LFVideoPlayer_Example' do
  pod 'CTM_LFVideoPlayer', :path => '../'

  target 'CTM_LFVideoPlayer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
